server:
  address: localhost
  port: 8080

spring:
  application:
    name: data-service

ribbon:
  eureka:
    enabled: true

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

#we tell the Eureka Client the sever url
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# the eureka client will send heart beats every 10 seconds, default is 30 seconds
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    ipAddress: ${server.address}
    instanceId: ${server.address}:${server.port}