server:
  port: 8083

spring:
  application:
    name: review-service

#we tell the Eureka Client the sever url
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# the eureka client will send heart beats every 10 seconds, default is 30 seconds
  instance:
    leaseRenewalIntervalInSeconds: 10

# An Eureka instance is indentified by eureka.instance.instanceId
# if not used eureka.instance.metadataMap.instanceId will be it should be unique
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
